[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

bscMainnet = "https://bsc-dataseed.bnbchain.org"
bscTestnet = "https://bsc-testnet-dataseed.bnbchain.org"
opBNBTestnet = "https://opbnb-testnet-rpc.bnbchain.org/"
greenfieldTestnet = "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
