[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
default_network = "http://127.0.0.1:8545"
localhost = "http://127.0.0.1:8545"

bscMainnet = "https://bsc-dataseed.bnbchain.org"
bscTestnet = "https://bsc-testnet-dataseed.bnbchain.org"
opBNBTestnet = "https://opbnb-testnet-rpc.bnbchain.org/"
greenfieldTestnet = "https://gnfd-testnet-fullnode-tendermint-us.bnbchain.org"

[etherscan]
bscTestnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
multiline_func_header = "params_first"
line_length = 80
tab_width = 2
quote_style = "double"
bracket_spacing = true
int_types = "long"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
